local root=vim.fn.getcwd()
vim.opt.rtp:prepend(root)
local tmp=vim.fn.tempname()
vim.fn.mkdir(tmp,'p')
local function check(value,message) assert(value,message) end
local coffe=require('coffe')
vim.g.mapleader=' '
vim.keymap.set('n','<leader>ff','<cmd>echo "existing"<CR>',{desc='existing mapping'})
coffe.setup({dashboard=false,undo=false,config_file=tmp..'/settings.lua'})
check(vim.g.colors_name=='coffe','default theme')
check(vim.fn.maparg('<leader>ff','n'):find('existing',1,true),'preserve existing keymap')
check(vim.fn.maparg('u','n')=='','native undo preserved')
check(vim.fn.maparg('<C-r>','n')=='','native redo preserved')
check(vim.fn.maparg('<C-v>','n')=='','native visual block preserved')
vim.fn.writefile({'hello world'},tmp..'/hello.txt')
vim.fn.mkdir(tmp..'/folder','p')
vim.cmd.cd(vim.fn.fnameescape(tmp))
require('coffe.util').edit(tmp..'/hello.txt')
local edited=vim.api.nvim_get_current_buf()
vim.cmd('normal! A changed')
check(vim.bo.modified,'text changed')
vim.cmd('undo')
check(vim.api.nvim_get_current_line()=='hello world','undo restores text')
vim.cmd('redo')
check(vim.api.nvim_get_current_line()=='hello world changed','redo restores edit')
vim.cmd('write')
check(vim.fn.readfile(tmp..'/hello.txt')[1]=='hello world changed','save writes disk')
local tree=require('coffe.explorer')
tree.open()
check(vim.api.nvim_win_is_valid(tree.win),'tree opens')
check(vim.api.nvim_get_current_win()==tree.win,'tree receives focus')
check(vim.api.nvim_win_get_position(tree.win)[2]==0,'tree on left')
local first_row
for row in pairs(tree.entries) do if not first_row or row < first_row then first_row = row end end
local first_entry = tree.entries[first_row]
check(first_entry and first_entry.name == 'folder','directories first')
vim.api.nvim_set_current_win(tree.win)
local fileline
for line,item in pairs(tree.entries) do if item.name=='hello.txt' then fileline=line end end
vim.api.nvim_win_set_cursor(tree.win,{fileline,0})
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>',true,false,true),'xt',false)
check(vim.api.nvim_get_current_buf()==edited,'open file from sidebar in editor')
tree.close(); check(not tree.win,'tree closes')
coffe.setup({dashboard=false,undo=false,explorer={side='right'}})
tree.open(); check(vim.api.nvim_win_get_position(tree.win)[2]>0,'tree on right'); tree.close()
local picked
local picker=require('coffe.picker').open('Test',{{label='alpha'},{label='beta'}},function(item) picked=item.label end)
vim.api.nvim_feedkeys('b','xt',false)
check(vim.api.nvim_buf_get_lines(picker.buf,2,3,false)[1]:find('beta',1,true),'picker filters')
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>',true,false,true),'xt',false)
check(picked=='beta','picker accepts selected result')
vim.api.nvim_buf_set_lines(0,0,-1,false,{'unsaved'})
require('coffe.dashboard').open()
check(vim.bo.filetype=='coffe','dashboard opens')
check(vim.bo[edited].modified,'dashboard keeps unsaved buffer')
check(vim.api.nvim_buf_get_lines(edited,0,1,false)[1]=='unsaved','unsaved text preserved')
coffe.setup({dashboard=false,undo=false,config_file=tmp..'/config.lua'})
vim.fn.writefile({'return {}'}, tmp..'/config.lua')
require('coffe.actions').settings()
check(type(dofile(tmp..'/config.lua'))=='table','settings is valid Lua')
local oldinput=vim.ui.input
vim.ui.input=function(_,cb) cb(tmp..'/new project') end
require('coffe.projects').create()
check(vim.uv.fs_realpath(vim.fn.getcwd())==vim.uv.fs_realpath(tmp..'/new project'),'project created with spaces and opened')
check(vim.fn.isdirectory(tmp..'/new project')==1,'project exists')
vim.ui.input=oldinput
tree.close()
coffe.setup({dashboard=false,undo=false,mappings=false})
check(vim.fn.maparg('<leader>e','n')=='','setup removes owned mappings')
check(vim.fn.maparg('<leader>ff','n'):find('existing',1,true),'setup keeps external mappings')
vim.cmd.cd(vim.fn.fnameescape(root))
print('Coffe smoke tests: PASS')
vim.cmd('qa!')
